### PR TITLE
Rework

### PR DESCRIPTION
**Pull request by steveklabnik**
This is a complete re-write of thanks, after https://github.com/rust-lang-nursery/thanks/issues/15#issuecomment-291199041. basically, we keep a local git repo and use it as our database, rather than sync everything to postgres. Why duplicate all of this stuff when this actually works?

This code is bad. I just hacked it together. There's several good ways to clean it up.

- [ ] error handling
- [x] extract stuff out of route handlers and into the libraries
- [x] release note links are gone
- [ ] some mailmap regressions, it seems
- [x] gotta bring back all the travis stuff
- [x]  heroku stuff, like port number

### CODE REVIEW

**Comment by russmack** [comment]
@steveklabnik Quick catchup briefing please - what's the status of this project, and is this the branch to work from?

**Comment by steveklabnik** [comment]
Hey @russmack !

Current status is: I still want to do a bunch of this, but have not had any time. If you're interested in working on Thanks, maybe we should chat about it? I'd love to see someone take the ball and run with it, as it were.

**Comment by russmack** [comment]
Hey Steve, the last time I looked at Thanks was March.  At around that time someone did some work replacing postgres with git for "populate", pr 97.  So this branch looks like it's more completely replacing potegres with git, finishing the cleanup list above - error handling and mailmap regressions - and then the issues list.  Yes?

**Comment by steveklabnik** [comment]
>  So this branch looks like it's more completely replacing potegres with git, finishing the cleanup list above - error handling and mailmap regressions - and then the issues list. Yes?

Basically, yes. Using the repo directly seems like the right call. However, I got slightly distracted; I wanted to try to also port this away from bare hyper and use some sort of framework.

Generally speaking, if you're interested in taking this forward, I would accept either finishing off this branch, or a re-do that focuses on using the git repo directly instead of postgres. Do you have any thoughts on that?

**Comment by steveklabnik** [comment]
Sparkles is sadly not ready, yeah :(

I'd prefer not to regress to nightly with Rocket; I'd been meaning to try Gotham. Frankly, I care more about sticking to stable than I do which particular framework.

**Comment by russmack** [comment]
Didn't realise Rocket wants nightly - Gotham it is.  Yeah, I'll take that commit bit. :)

**Comment by steveklabnik** [comment]
🤘

**Comment by steveklabnik** [comment]
Let me uh, close this PR since it's never going to be merged in its current state.

**Pull request closed without merging**
