### PR TITLE
Fix building binaries

### PR DESCRIPTION
**Pull request by jmatraszek**
Fixing. Was broken by https://github.com/rust-lang-nursery/thanks/commit/2930ab82bac9dafd99c9bf171ef4a6919b877fe5

### CODE REVIEW

**Comment by steveklabnik** [comment]
Actually, could you just remove the `path` lines? it should work without them. I like to only configure what's not conventional.

Thanks for this! Should have done a better job of double checking. I assumed that the "build" would have taken care of it...

**Comment by jmatraszek** [comment]
Removed. However, this gives me a warning: `warning: file found to be present in multiple build targets: /home/kuba/dev/contributors/src/main.rs` -- do not know if this is something we should worry about + cannot test the binaries as currently `cargo` fails to compile the project (still figuring out why).

**Comment by steveklabnik** [comment]
Hmm, that does seem bad. @alexcrichton do you have any recommendations for what this configuration is supposed to look like?

**Comment by jmatraszek** [comment]
In fact, achieved to build the project, but running bin (without path specified in `Cargo.toml`) is not possible:
```$ rustup run nightly cargo run --bin populate --     
warning: file found to be present in multiple build targets: /home/kuba/dev/contributors/src/main.rs
[...]
     Running `target/debug/populate`
Listening on http://0.0.0.0:1337```

When path is specified it works ok:
```$ rustup run nightly cargo run --bin populate -- 
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target/debug/populate`
error: The following required arguments were not provided:
    --path <filepath>```

Anyway, waiting for Alex to comment on this, if there is no better way to achieve this, then I can revert the last commit.

**Comment by alexcrichton** [comment]
Weird! That sounds like it may be a bug in Cargo...

**Comment by steveklabnik** [comment]
@jmatraszek okay so, let's revert that last commit to get rid of the warning for now, and maybe we'll end up filing a cargo bug.

sorry that this simple PR has taken so long.

**Comment by steveklabnik** [comment]
@jmatraszek actually, don't worry about it; I did some work on those binaries in https://github.com/rust-lang-nursery/thanks/pull/53 and so just rolled all the commits except the last one into there. Thank you so much again!

**Comment by jmatraszek** [comment]
Hi @steveklabnik, @alexcrichton,
Played with Cargo yesterday and I ended up fixing this: https://github.com/rust-lang/cargo/pull/3609

**Pull request closed without merging**
